### ISSUE TITLE
What are the commands?

### ISSUE THREAD

**Issue by lXndr6** [FortunesFavor/polyhedral#6]
I tried something out, tried to understand whats in the code, but i cant give any commands to polyhedral.
Please extend the readme.

**Comment by tritium21** [comment]
There is a new pseudo-client named *polyhedral (or whatever your prefix character is).

```
/msg *polyhedral add #channel !trigger
```

The dice syntax is controlled by another package, but will always support 1d20 syntax.  In that channel, use `!trigger 4d6` or whatever dice command you want to use.
